import Head from "next/head";
import Banner from "../components/Banner";
import Card from "../components/Card";
import LargeCard from "../components/LargeCard";
import SmallCard from "../components/SmallCard";
import { useRouter } from "next/router";
import Header from "../components/Header";

export default function Home({ data, cardsData }) {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>AirBnb clone</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <Banner />

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {data?.map((item, index) => (
              <SmallCard
                image={item.img}
                location={item.location}
                distance={item.distance}
                key={index}
              />
            ))}
          </div>
        </section>

        <section>
          <h2 className='text-4xl font-semibold py-8'>Live Anywhere</h2>
          <div className='flex overflow-x-scroll space-x-3 scrollbar-hide p-3 -ml-3'>
            {cardsData?.map((card, index) => (
              <Card key={index} image={card.img} title={card.title} />
            ))}
          </div>
        </section>
        <LargeCard
          image='https://links.papareact.com/4cj'
          title='The Greatest outdoors'
          description='Wishlists curated by Airbnb.'
          buttonText='Get Inspired'
        />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const exploredData = await fetch("https://links.papareact.com/pyp").then(
    (result) => result.json()
  );

  const cardsData = await fetch("https://links.papareact.com/zp1").then(
    (result) => result.json()
  );

  return {
    props: {
      data: exploredData,
      cardsData: cardsData,
    },
  };
}
